<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-MUD8M4ML" name="com.AdjunoGeorgeFoundation.Test.CheckEndToEndFunctionalityTest" tests="4" failures="1" timestamp="22 May 2018 05:34:18 GMT" time="35.714" errors="0">
  <testcase name="test_1_LaunchTheBrowser" time="15.485" classname="com.AdjunoGeorgeFoundation.Test.CheckEndToEndFunctionalityTest"/>
  <testcase name="test_2_LoginWithIncorrectCredentials" time="1.515" classname="com.AdjunoGeorgeFoundation.Test.CheckEndToEndFunctionalityTest"/>
  <testcase name="test_4_SearchProductFromAutosuggestionBox" time="9.374" classname="com.AdjunoGeorgeFoundation.Test.CheckEndToEndFunctionalityTest"/>
  <testcase name="test_3_LoginWithCorrectCredentials" time="9.340" classname="com.AdjunoGeorgeFoundation.Test.CheckEndToEndFunctionalityTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	***** test_3_ In FlipKart application the user name is incorrect ***** expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	***** test_3_ In FlipKart application the user name is incorrect ***** expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.AdjunoGeorgeFoundation.Test.CheckEndToEndFunctionalityTest.test_3_LoginWithCorrectCredentials(CheckEndToEndFunctionalityTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- test_3_LoginWithCorrectCredentials -->
</testsuite> <!-- com.AdjunoGeorgeFoundation.Test.CheckEndToEndFunctionalityTest -->
